---
title: "Lending Mortage Analysis"
author: "Marjorie Blanco, Joe Thompson, Haodi Tu"
output:
  html_document: default
  pdf_document: default
subtitle: Exploratory Data Analysis
geometry: left=2cm,right=3cm,top=2cm,bottom=2cm
---


```{r warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(scipen=999)
library(readr)
library(ggplot2)
library(readxl)
library(kableExtra)
library(dplyr)
library(tidyverse)
library(purrr)
library(ggthemes)
library(aod)
library(lmtest)
library(survey)
library(caret)
```

```{r}
data <- read_excel("MLD/MLD Data File.xls")

#data <- read_excel("MLD Data File.xls")

data <- tibble::rowid_to_column(data, "ID")
data$RACE <- ifelse(data$BLACK == 1, "non-Hispanic Black", ifelse(data$HISPAN == 1, "Hispanic", "non-Hispanic White"))


data  <- data %>% mutate(MARRIED = ifelse(MARRIED == 1, "Yes", ifelse(MARRIED == 0, "No", "Unknown")))
data  <- data %>% mutate(BLACK = ifelse(BLACK == 1, "Yes", ifelse(BLACK == 0, "No", "Unknown")))
data  <- data %>% mutate(HISPAN = ifelse(HISPAN == 1, "Yes", ifelse(HISPAN == 0, "No", "Unknown")))
data  <- data %>% mutate(APPROVE = ifelse(APPROVE == 1, "Yes", ifelse(APPROVE == 0, "No", "Unknown")))
data  <- data %>% mutate(MALE = ifelse(MALE == 1, "Yes", ifelse(MALE == 0, "No", "Unknown")))
data$LOANPRC <- data$LOANPRC * 100

data$MARRIED <- as.factor(data$MARRIED)
data$MALE <- as.factor(data$MALE)
data$APPROVE <- as.factor(data$APPROVE)
data$GDLIN <- as.factor(data$GDLIN)
data$BLACK <- as.factor(data$BLACK)
data$HISPAN <- as.factor(data$HISPAN)

data$RACE <- as.factor(data$RACE)
data1 <- data

colnames(data1) <- c("ID", "Married", "Meet credit history guidelines",  "Other obligations as a percent of total income", "non-Hispanic Black",  "Hispanic", "Male", "Mortgage loan approved", "Loan amount/purchase price", "Race")

```
The data set contains `r nrow(data)` records.  The overall descriptive statistics:

```{r}
summary(data1[,2:10])
```

Descriptive statistics by Race:

```{r}
data %>% select(-c(ID, BLACK, HISPAN)) %>% split(.$RACE) %>% map(summary) 
```

```{r}
ggplot(data,  aes(OBRAT)) +
  geom_histogram(binwidth = 1)  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 0, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  facet_grid(RACE ~ ., scales="free")



data1 <- data

data1$OBRAT<-cut(data1$OBRAT, seq(0,95,1))
data1$LOANPRC<-cut(data1$LOANPRC, seq(0,260,5))


ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "Hispanic"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "non-Hispanic Black"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "non-Hispanic White"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MALE == "Yes"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MALE ~ ., scales="free", labeller = as_labeller(c(Yes = "Male"))) +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MALE == "No"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MALE ~ ., scales="free", labeller = as_labeller(c(No = "Female"))) +
  theme(legend.position="bottom") 


ggplot() +
  geom_bar(data = data1 %>% filter(MARRIED == "Yes"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MARRIED ~ ., scales="free", labeller = as_labeller(c(Yes = "Married"))) +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MARRIED == "No"),  aes(x = OBRAT, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Other obligations as a percent of total income") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MARRIED ~ ., scales="free", labeller = as_labeller(c(No = "Not Married"))) +
  theme(legend.position="bottom")
```

```{r}
ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "Hispanic"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "non-Hispanic Black"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(RACE == "non-Hispanic White"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(RACE ~ ., scales="free") +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MALE == "Yes"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MALE ~ ., scales="free", labeller = as_labeller(c(Yes = "Male"))) +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MALE == "No"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MALE ~ ., scales="free", labeller = as_labeller(c(No = "Female"))) +
  theme(legend.position="bottom")


ggplot() +
  geom_bar(data = data1 %>% filter(MARRIED == "Yes"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MARRIED ~ ., scales="free", labeller = as_labeller(c(Yes = "Married"))) +
  theme(legend.position="bottom")

ggplot() +
  geom_bar(data = data1 %>% filter(MARRIED == "No"),  aes(x = LOANPRC, fill = APPROVE), position = "fill")  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Loan amount/purchase price %") +
  scale_y_continuous("Percent") +
  scale_fill_manual(values = c("red", "green")) +
  facet_grid(MARRIED ~ ., scales="free", labeller = as_labeller(c(No = "Not Married"))) +
  theme(legend.position="bottom")
```

Descriptive statistics by Marital Status:

```{r}
data %>% select(-c(ID, BLACK, HISPAN)) %>% split(.$MARRIED) %>% map(summary)
```

Descriptive statistics by Gender:

```{r}
data %>% select(-c(ID, BLACK, HISPAN)) %>% split(.$MALE) %>% map(summary)
```


There are 3 records are missing married (MARRIED) field.

```{r}
kable(data %>% filter(MARRIED == "Unknown"))  %>%
  kable_styling(bootstrap_options = "striped")
```

There are 3 records are missing married (GDLIN) field.

```{r}
kable(data %>% filter(GDLIN == "666"))  %>%
  kable_styling(bootstrap_options = "striped")
```

There are 15 records are missing gender (MALE) field.

```{r}
kable(data %>% filter(MALE == "Unknown"))  %>%
  kable_styling(bootstrap_options = "striped")
```

```{r}
xtabs(~RACE + APPROVE, data = data)


ggplot(data,  aes(RACE)) +
  geom_bar()  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 0, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Race")
```

```{r}
xtabs(~MARRIED + APPROVE, data = data)

ggplot(data,  aes(MARRIED)) +
  geom_bar()  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 0, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Married")
```

```{r}
xtabs(~MALE + APPROVE, data = data)

ggplot(data,  aes(MALE)) +
  geom_bar()  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 0, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Male")
```

```{r}
xtabs(~MARRIED + APPROVE + RACE, data = data)


ggplot(data,  aes(RACE, fill = MALE)) +
  geom_bar()  +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 0, vjust = 1, 
                                   size = 12, hjust = 1)) + 
  xlab("Race")
```

```{r}
t1 <- theme_tufte() + theme(axis.text.x = element_text( hjust = 1)) #angle = 90,

c <- ggplot(data, aes(y = LOANPRC)) + t1

c + geom_boxplot(aes(x=RACE, color=RACE), trim = FALSE)
c + geom_boxplot(aes(x=MARRIED, color=RACE), trim = FALSE)
c + geom_boxplot(aes(x=MALE, color=RACE), trim = FALSE)
c + geom_boxplot(aes(x=RACE, color=APPROVE), trim = FALSE)

```

```{r}
data <- read_excel("MLD/MLD Data File.xls")
```

```{r}
data$MARRIED <- NULL 
data <- data %>% filter(MALE != ".") %>% filter(GDLIN != "666")
data$LOANPRC <- data$LOANPRC * 100
data$GDLIN <- as.factor(data$GDLIN)

data$MALE <- as.factor(data$MALE)
data$APPROVE <- as.factor(data$APPROVE)
data$BLACK <- as.factor(data$BLACK)
data$HISPAN <- as.factor(data$HISPAN)

mylogit <- glm(APPROVE ~  GDLIN + OBRAT + BLACK + HISPAN + MALE + LOANPRC , data = data, family = "binomial")
mylogit
```

```{r}
confint(mylogit)
confint.default(mylogit)
exp(coef(mylogit))
exp(cbind(OR = coef(mylogit), confint(mylogit)))

```

```{r}
#newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = 86.05))

# non-Hispanic Black Male
x <- mean(data$LOANPRC)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(1), LOANPRC = x))

newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic Black Male Predicted probabilities")


# non-Hispanic Black Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(0), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic Black Female Predicted probabilities")
```

```{r}   
# Hispanic Male
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(1), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Hispanic Male Predicted probabilities")
```

```{r}     
# Hispanic Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(0), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Hispanic Female Predicted probabilities")
```

```{r} 
# White Male
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(1), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + geom_ribbon(aes(ymin = LL,
                                                                      ymax = UL, fill = GDLIN), alpha = 0.2) + geom_line(aes(colour = GDLIN),
                                                                                                                         size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic White Male Predicted probabilities")
```

```{r}     
# White Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(0), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = OBRAT, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic White Female Predicted probabilities")
```


```{r}
#newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = 86.05))

# non-Hispanic Black Male
x <- mean(data$OBRAT)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(1), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic Black Male Predicted probabilities")


# non-Hispanic Black Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(0), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic Black Female Predicted probabilities")
```

```{r}   
# Hispanic Male
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(1), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Hispanic Male Predicted probabilities")
```

```{r}     
# Hispanic Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(1), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Hispanic Female Predicted probabilities")
```

```{r} 
# White Male
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(1), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) +
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic White Male Predicted probabilities")
```

```{r}     
# White Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(0), OBRAT = x))
newdata3 <- cbind(newdata2, predict(mylogit, newdata = newdata2, type = "link", se = TRUE))
newdata3 <- within(newdata3, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

ggplot(newdata3, aes(x = LOANPRC, y = PredictedProb)) + 
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = GDLIN), alpha = 0.2) +
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic White Female Predicted probabilities")
```


```{r}
mylogit <- glm(APPROVE ~  GDLIN + OBRAT + BLACK + HISPAN  + LOANPRC , data = data, family = "binomial")
mylogit
```

```{r}
myprobit1 <- glm(APPROVE ~  GDLIN + OBRAT + BLACK + HISPAN + MALE + LOANPRC , data = data, family = binomial(link = "probit"))
myprobit1
varImp(myprobit1)
```

```{r}
myprobit2 <- glm(APPROVE ~  GDLIN + OBRAT + BLACK + HISPAN  + LOANPRC , data = data, family = binomial(link = "probit"))
myprobit2
varImp(myprobit2)
```

```{r}
anova(myprobit1, myprobit2, test ="Chisq")
lrtest(myprobit1, myprobit2)
```

```{r}
myprobit3 <- glm(APPROVE ~  GDLIN  + BLACK + HISPAN + MALE + LOANPRC , data = data, family = binomial(link = "probit"))
myprobit3
varImp(myprobit3)
```


```{r}
anova(myprobit1, myprobit3, test ="Chisq")
lrtest(myprobit1, myprobit3)
```

```{r}
myprobit4 <- glm(APPROVE ~  GDLIN  + BLACK + HISPAN  + LOANPRC , data = data, family = binomial(link = "probit"))
myprobit4
varImp(myprobit4)
```


```{r}
anova(myprobit1, myprobit4, test ="Chisq")
lrtest(myprobit1, myprobit4)
```


```{r}
# non-Hispanic Black Male/Female
x <- mean(data$LOANPRC)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic Black Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic Black Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```

```{r}
# Hispanic Male/Female
x <- mean(data$LOANPRC)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Hispanic Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Hispanic Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```

```{r}
# White Male/Female
x <- mean(data$LOANPRC)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic White Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("non-Hispanic White Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```

```{r}
# non-Hispanic Black Male/Female
x <- mean(data$OBRAT)
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 100)), OBRAT = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic Black Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic Black Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```

```{r}
# non-Hispanic Hispanic Male/Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(rep(0:1, each = 100)), OBRAT = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Hispanic Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Hispanic Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```

```{r}
# White Male/Female
newdata2 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(rep(0:1, each = 100)), OBRAT = x))
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")

ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = MALE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic White Black Predicted probabilities") + 
  facet_grid(GDLIN ~ .) +
  ylab("PredictedProb")


ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = GDLIN), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("non-Hispanic White Black Predicted probabilities") + 
  facet_wrap(MALE ~ .) +
  ylab("PredictedProb")
```



```{r}
#
x <- mean(data$LOANPRC)
newdata21 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))
newdata22 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))
newdata23 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 192)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(rep(0:1, each = 96)), LOANPRC = x))

newdata2 <- rbind(newdata21, newdata22, newdata23)
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])

newdata3$RACE <- ifelse(newdata3$BLACK == 1, "non-Hispanic Black", ifelse(newdata3$HISPAN == 1, "Hispanic", "non-Hispanic White"))
newdata3$RACE  <- as.factor(newdata3$RACE)
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")


ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ MALE, scales="free") +
  ylab("PredictedProb")
```


```{r}
#
x <- mean(data$OBRAT)
newdata21 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(1), HISPAN = factor(0), MALE = factor(rep(0:1, each = 100)), OBRAT = x))
newdata22 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(1), MALE = factor(rep(0:1, each = 100)), OBRAT = x))
newdata23 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 200)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(0), MALE = factor(rep(0:1, each = 100)), OBRAT = x))

newdata2 <- rbind(newdata21, newdata22, newdata23)
newdata3 <- cbind(newdata2, predict(myprobit1, newdata2, type = "response", se.fit = TRUE)[-3])

newdata3$RACE <- ifelse(newdata3$BLACK == 1, "non-Hispanic Black", ifelse(newdata3$HISPAN == 1, "Hispanic", "non-Hispanic White"))
newdata3$RACE  <- as.factor(newdata3$RACE)
newdata3$MALE <- ifelse(newdata3$MALE == 1, "Male", "Female")
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")


ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ MALE, scales="free") +
  ylab("PredictedProb")
```



```{r}
#
x <- mean(data$LOANPRC)
newdata21 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(1), HISPAN = factor(0), LOANPRC = x))
newdata22 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(1), LOANPRC = x))
newdata23 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 96)), OBRAT = rep(seq(from = 0, to = 95, length.out = 96)), BLACK = factor(0), HISPAN = factor(0), LOANPRC = x))

newdata2 <- rbind(newdata21, newdata22, newdata23)
newdata3 <- cbind(newdata2, predict(myprobit2, newdata2, type = "response", se.fit = TRUE)[-3])

newdata3$RACE <- ifelse(newdata3$BLACK == 1, "non-Hispanic Black", ifelse(newdata3$HISPAN == 1, "Hispanic", "non-Hispanic White"))
newdata3$RACE  <- as.factor(newdata3$RACE)
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")

ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ RACE) +
  ylab("PredictedProb")

ggplot(newdata3, aes(x = OBRAT, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Other obligations as a percent of total income") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ ., scales="free") +
  ylab("PredictedProb")
```


```{r}
#
x <- mean(data$OBRAT)
newdata21 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(1), HISPAN = factor(0), OBRAT = x))
newdata22 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(1), OBRAT = x))
newdata23 <- with(data, data.frame(GDLIN = factor(rep(0:1, each = 100)), LOANPRC = rep(seq(from = 2.105, to = 257.143, length.out = 100)), BLACK = factor(0), HISPAN = factor(0), OBRAT = x))

newdata2 <- rbind(newdata21, newdata22, newdata23)
newdata3 <- cbind(newdata2, predict(myprobit2, newdata2, type = "response", se.fit = TRUE)[-3])

newdata3$RACE <- ifelse(newdata3$BLACK == 1, "non-Hispanic Black", ifelse(newdata3$HISPAN == 1, "Hispanic", "non-Hispanic White"))
newdata3$RACE  <- as.factor(newdata3$RACE)
newdata3$GDLIN <- ifelse(newdata3$GDLIN == 1, "Meets guidelines", "Does not meet guidelines")

ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ RACE) +
  ylab("PredictedProb")

ggplot(newdata3, aes(x = LOANPRC, y = fit)) + 
  geom_line(aes(colour = RACE), size = 1)  +
  theme(legend.position="bottom") +
  xlab("Loan amount/purchase price %") +
  ggtitle("Predicted probabilities") + 
  facet_wrap(GDLIN ~ ., scales="free") +
  ylab("PredictedProb")
```